# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: lowkey.api
services:
  
- name: lowkey
  image: nagyesta/lowkey-vault:2.1.0-jammy
  bindings:
    - port: 8443
      connectionString: ${host}:${port}
  volumes:
    - source: ./.local/lowkey/import
      target: /import
    - source: ./.local/lowkey/config
      target: /config
#  env:
#    - name: LOWKEY_ARGS
#      value: >
#        --server.port=8443
#        --LOWKEY_DEBUG_REQUEST_LOG=true 
##        --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs 
##        --LOWKEY_IMPORT_TEMPLATE_HOST=localhost 
##        --LOWKEY_IMPORT_TEMPLATE_PORT=8443
#  #        --server.ssl.key-store-type=JKS 
#  #        --server.ssl.key-store=/config/cert.jks 
#  #        --server.ssl.key-store-password=password 
#  #        --LOWKEY_VAULT_NAMES=- 
#  
  
  
  
- name: lowkey-api
  project: src/LowKey.API/LowKey.API.csproj
  bindings:
    - port: 18789
      name: http
      protocol: http
    - port: 18790
      name: https
      protocol: https
  env:
    - ASPNETCORE_ENVIRONMENT=Development